#!/bin/bash

if ps ux | grep drm.py | grep -v grep > /dev/null; then
	# an instance is already running
	echo "'drm' is already running."
	exit 1
fi

if [ ! -d $HOME/.dsromsmanager ]; then
	mkdir $HOME/.dsromsmanager
fi

cd /usr/share/dsromsmanager/
python -OO ./drm.py
